version: "3"

services:
  tradeogre_archive:
    image: makeshift/tradeogre_archive
    build: .
    restart: always
    environment:
      outputPrefix: /outputs/
      orderList: LTC-XLA,BTC-DOGE
    volumes:
      - ./outputs:/outputs
